// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentMessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sentMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* DescribedMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DescribedMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sentMessage_2eproto() {
  protobuf_AddDesc_sentMessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sentMessage.proto");
  GOOGLE_CHECK(file != NULL);
  DescribedMessage_descriptor_ = file->message_type(0);
  static const int DescribedMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescribedMessage, full_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescribedMessage, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescribedMessage, debug_msg_),
  };
  DescribedMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DescribedMessage_descriptor_,
      DescribedMessage::default_instance_,
      DescribedMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescribedMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescribedMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DescribedMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sentMessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DescribedMessage_descriptor_, &DescribedMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sentMessage_2eproto() {
  delete DescribedMessage::default_instance_;
  delete DescribedMessage_reflection_;
}

void protobuf_AddDesc_sentMessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021sentMessage.proto\"I\n\020DescribedMessage\022"
    "\021\n\tfull_name\030\001 \002(\t\022\017\n\007message\030\002 \002(\014\022\021\n\td"
    "ebug_msg\030\003 \001(\t", 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sentMessage.proto", &protobuf_RegisterTypes);
  DescribedMessage::default_instance_ = new DescribedMessage();
  DescribedMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sentMessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sentMessage_2eproto {
  StaticDescriptorInitializer_sentMessage_2eproto() {
    protobuf_AddDesc_sentMessage_2eproto();
  }
} static_descriptor_initializer_sentMessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DescribedMessage::kFullNameFieldNumber;
const int DescribedMessage::kMessageFieldNumber;
const int DescribedMessage::kDebugMsgFieldNumber;
#endif  // !_MSC_VER

DescribedMessage::DescribedMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DescribedMessage)
}

void DescribedMessage::InitAsDefaultInstance() {
}

DescribedMessage::DescribedMessage(const DescribedMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DescribedMessage)
}

void DescribedMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  full_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  debug_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DescribedMessage::~DescribedMessage() {
  // @@protoc_insertion_point(destructor:DescribedMessage)
  SharedDtor();
}

void DescribedMessage::SharedDtor() {
  if (full_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete full_name_;
  }
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (debug_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete debug_msg_;
  }
  if (this != default_instance_) {
  }
}

void DescribedMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DescribedMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DescribedMessage_descriptor_;
}

const DescribedMessage& DescribedMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sentMessage_2eproto();
  return *default_instance_;
}

DescribedMessage* DescribedMessage::default_instance_ = NULL;

DescribedMessage* DescribedMessage::New() const {
  return new DescribedMessage;
}

void DescribedMessage::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_full_name()) {
      if (full_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        full_name_->clear();
      }
    }
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        message_->clear();
      }
    }
    if (has_debug_msg()) {
      if (debug_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        debug_msg_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DescribedMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DescribedMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string full_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_full_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->full_name().data(), this->full_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "full_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_message;
        break;
      }

      // required bytes message = 2;
      case 2: {
        if (tag == 18) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_message()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_debug_msg;
        break;
      }

      // optional string debug_msg = 3;
      case 3: {
        if (tag == 26) {
         parse_debug_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_debug_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->debug_msg().data(), this->debug_msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "debug_msg");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DescribedMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DescribedMessage)
  return false;
#undef DO_
}

void DescribedMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DescribedMessage)
  // required string full_name = 1;
  if (has_full_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->full_name().data(), this->full_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "full_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->full_name(), output);
  }

  // required bytes message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->message(), output);
  }

  // optional string debug_msg = 3;
  if (has_debug_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->debug_msg().data(), this->debug_msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "debug_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->debug_msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DescribedMessage)
}

::google::protobuf::uint8* DescribedMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DescribedMessage)
  // required string full_name = 1;
  if (has_full_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->full_name().data(), this->full_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "full_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->full_name(), target);
  }

  // required bytes message = 2;
  if (has_message()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->message(), target);
  }

  // optional string debug_msg = 3;
  if (has_debug_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->debug_msg().data(), this->debug_msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "debug_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->debug_msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DescribedMessage)
  return target;
}

int DescribedMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string full_name = 1;
    if (has_full_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->full_name());
    }

    // required bytes message = 2;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->message());
    }

    // optional string debug_msg = 3;
    if (has_debug_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->debug_msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DescribedMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DescribedMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DescribedMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DescribedMessage::MergeFrom(const DescribedMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_full_name()) {
      set_full_name(from.full_name());
    }
    if (from.has_message()) {
      set_message(from.message());
    }
    if (from.has_debug_msg()) {
      set_debug_msg(from.debug_msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DescribedMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DescribedMessage::CopyFrom(const DescribedMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DescribedMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void DescribedMessage::Swap(DescribedMessage* other) {
  if (other != this) {
    std::swap(full_name_, other->full_name_);
    std::swap(message_, other->message_);
    std::swap(debug_msg_, other->debug_msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DescribedMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DescribedMessage_descriptor_;
  metadata.reflection = DescribedMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
